export default function Head() {
  return (
    <>
      <title>Software Development company | GoodCore London, UK</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link
        rel="icon"
        href="https://cdn-addgm.nitrocdn.com/MJnTlHySegcmvxPTBPLfaINTSJyWuhDi/assets/images/optimized/rev-9075f04/assets/img/favicon.ico"
      />
    </>
  );
}
